import yaml
from bot.parser import ParamRecord
from bot.emitter import emit_data_text


def test_krkn_hub_omits_absent_optional_fields():
    recs = [
        ParamRecord(name="ACTION", default="node_stop", type="enum"),
        ParamRecord(name="EXCLUDE_LABEL", type="string"),
    ]
    descs = {"ACTION": "Action to run.", "EXCLUDE_LABEL": "Nodes to exclude."}
    text = emit_data_text("node-scenarios", "krkn-hub", recs, descs, source_ref="abc123")
    data = yaml.safe_load(text)
    assert data["source_repo"] == "krkn-hub"
    assert data["source_ref"] == "abc123"
    assert data["params"][0] == {
        "name": "ACTION", "description": "Action to run.", "type": "enum", "default": "node_stop",
    }
    assert "default" not in data["params"][1]
    assert "required" not in data["params"][0]


def test_krknctl_includes_required_and_possible_values():
    recs = [ParamRecord(name="CLOUD", type="enum", default="aws",
                        required=True, allowed_values=["aws", "gcp"])]
    descs = {"CLOUD": "Cloud platform."}
    text = emit_data_text("svc", "krknctl", recs, descs, source_ref="x")
    p = yaml.safe_load(text)["params"][0]
    assert p["possible_values"] == ["aws", "gcp"]
    assert p["required"] is True


def test_output_is_deterministic():
    recs = [ParamRecord(name="A", default="1", type="number")]
    descs = {"A": "An a."}
    t1 = emit_data_text("s", "krkn-hub", recs, descs, source_ref="r")
    t2 = emit_data_text("s", "krkn-hub", recs, descs, source_ref="r")
    assert t1 == t2
    assert t1.startswith("# Generated by krkn-docs-bot. Do not edit by hand.\n")


def test_grouped_krknctl_source_keeps_possible_values():
    """Globals emit under krknctl-<group>, and the page has a Possible Values column."""
    recs = [ParamRecord(name="triggers-mode", type="enum", default="all",
                        allowed_values=["all", "any"])]
    p = yaml.safe_load(emit_data_text(
        "globals", "krknctl-triggers", recs, {"triggers-mode": "How."}, "r"))["params"][0]
    assert p["possible_values"] == ["all", "any"]


def test_grouped_krknctl_source_omits_required():
    """All 72 global params are required=false, so emitting the field would add a
    sixth column of "False" to a five-column page."""
    recs = [ParamRecord(name="triggers-mode", allowed_values=["all"])]
    p = yaml.safe_load(emit_data_text(
        "globals", "krknctl-triggers", recs, {"triggers-mode": "How."}, "r"))["params"][0]
    assert "required" not in p
