import yaml
from bot.parser import ParamRecord
from bot.emitter import emit_data_text, load_descriptions


def test_krkn_hub_omits_absent_optional_fields():
    recs = [
        ParamRecord(name="ACTION", default="node_stop", type="enum"),
        ParamRecord(name="EXCLUDE_LABEL", type="string"),
    ]
    descs = {"ACTION": "Action to run.", "EXCLUDE_LABEL": "Nodes to exclude."}
    text = emit_data_text("node-scenarios", "krkn-hub", recs, descs, source_ref="abc123")
    data = yaml.safe_load(text)
    assert data["source_repo"] == "krkn-hub"
    assert data["source_ref"] == "abc123"
    assert data["params"][0] == {
        "name": "ACTION", "description": "Action to run.", "type": "enum", "default": "node_stop",
    }
    assert "default" not in data["params"][1]
    assert "required" not in data["params"][0]


def test_group_is_emitted_when_present():
    recs = [ParamRecord(name="wait-duration", default="1", group="general")]
    p = yaml.safe_load(emit_data_text(
        "globals", "krknctl", recs, {"wait-duration": "Waits."}, "r"))["params"][0]
    assert p["group"] == "general"


def test_group_is_omitted_when_absent():
    """Per-scenario params have no group and must not gain an empty key."""
    p = yaml.safe_load(emit_data_text(
        "node-scenarios", "krkn-hub", [ParamRecord(name="ACTION")],
        {"ACTION": "Act."}, "r"))["params"][0]
    assert "group" not in p


def test_krknctl_includes_required_and_possible_values():
    recs = [ParamRecord(name="CLOUD", type="enum", default="aws",
                        required=True, allowed_values=["aws", "gcp"])]
    descs = {"CLOUD": "Cloud platform."}
    text = emit_data_text("svc", "krknctl", recs, descs, source_ref="x")
    p = yaml.safe_load(text)["params"][0]
    assert p["possible_values"] == ["aws", "gcp"]
    assert p["required"] is True


def test_krknctl_rows_carry_the_cli_flag():
    """The krknctl page lists flags, but name stays the env var so the drift
    scanner and the skip list keep matching on it."""
    recs = [ParamRecord(name="ACTION", flag="action")]
    p = yaml.safe_load(emit_data_text(
        "node-scenarios", "krknctl", recs, {"ACTION": "Act."}, "r"))["params"][0]
    assert p["name"] == "ACTION"
    assert p["flag"] == "action"


def test_krkn_hub_rows_carry_no_flag():
    """env.sh params have no CLI flag and must not gain an empty key."""
    recs = [ParamRecord(name="ACTION", flag="action")]
    p = yaml.safe_load(emit_data_text(
        "node-scenarios", "krkn-hub", recs, {"ACTION": "Act."}, "r"))["params"][0]
    assert "flag" not in p


def test_a_flag_identical_to_the_name_is_not_duplicated():
    """globals swaps the flag into name and leaves flag set, so all 78 global
    rows would gain a key holding the same string."""
    recs = [ParamRecord(name="action", flag="action")]
    p = yaml.safe_load(emit_data_text(
        "globals", "krknctl", recs, {"action": "Act."}, "r"))["params"][0]
    assert "flag" not in p


def test_a_secret_param_is_marked_in_the_data():
    """The shortcode renders this as "string (secret)"."""
    recs = [ParamRecord(name="BMC_PASSWORD", flag="bmc-password",
                        type="string", secret=True)]
    p = yaml.safe_load(emit_data_text(
        "node-scenarios", "krknctl", recs, {"BMC_PASSWORD": "IPMI password."},
        "r"))["params"][0]
    assert p["secret"] is True


def test_a_non_secret_param_gains_no_key():
    recs = [ParamRecord(name="ACTION", flag="action", type="string")]
    p = yaml.safe_load(emit_data_text(
        "node-scenarios", "krknctl", recs, {"ACTION": "Act."}, "r"))["params"][0]
    assert "secret" not in p


def test_output_is_deterministic():
    recs = [ParamRecord(name="A", default="1", type="number")]
    descs = {"A": "An a."}
    t1 = emit_data_text("s", "krkn-hub", recs, descs, source_ref="r")
    t2 = emit_data_text("s", "krkn-hub", recs, descs, source_ref="r")
    assert t1 == t2
    assert t1.startswith("# Generated by krkn-docs-bot. Do not edit by hand.\n")


# load_descriptions lives next to the writer so any caller can read a data file.

def test_load_descriptions_round_trips_what_the_emitter_wrote(tmp_path):
    f = tmp_path / "krkn-hub.yaml"
    f.write_text(emit_data_text("s", "krkn-hub", [ParamRecord(name="A")],
                                {"A": "An a."}, "r"), encoding="utf-8")
    assert load_descriptions(f) == {"A": "An a."}


def test_load_descriptions_of_a_missing_file_is_empty(tmp_path):
    assert load_descriptions(tmp_path / "nope.yaml") == {}
