from unittest.mock import patch
import yaml
import bot.doc_bot as doc_bot


def _site(tmp_path):
    website = tmp_path / "site"
    (website / "content/en/docs/scenarios").mkdir(parents=True)
    (website / "content/en/docs/scenarios/all-scenario-env.md").write_text("", encoding="utf-8")
    return website


def _params(website, scenario, source="krkn-hub"):
    data = yaml.safe_load((website / f"data/params/{scenario}/{source}.yaml").read_text(encoding="utf-8"))
    return {p["name"]: p for p in data["params"]}


def test_env_description_filled_from_krknctl_json(tmp_path):
    hub = tmp_path / "hub"
    scn = hub / "node-scenarios"
    scn.mkdir(parents=True)
    (scn / "env.sh").write_text('export FOO="${FOO:-x}"\n', encoding="utf-8")
    (scn / "krknctl-input.json").write_text(
        '[{"variable": "FOO", "description": "controls the foo behaviour", "default": "x"}]',
        encoding="utf-8")
    website = _site(tmp_path)

    doc_bot.run(scenario="node-scenarios", krkn_hub_root=hub, website_root=website)

    assert _params(website, "node-scenarios")["FOO"]["description"] == "controls the foo behaviour"


def test_env_only_param_is_left_blank_not_papered_over(tmp_path):
    hub = tmp_path / "hub"
    scn = hub / "node-scenarios"
    scn.mkdir(parents=True)
    (scn / "env.sh").write_text('export BAR="${BAR:-y}"\n', encoding="utf-8")
    (scn / "krknctl-input.json").write_text('[{"variable": "OTHER", "description": "x"}]', encoding="utf-8")
    website = _site(tmp_path)
    doc_bot.run(scenario="node-scenarios", krkn_hub_root=hub, website_root=website)
    # Was "Configures bar." That reads as finished while saying nothing, hiding
    # the gap. Blank shows a human there is work to do.
    assert _params(website, "node-scenarios")["BAR"]["description"] == ""


def test_source_wins_over_the_committed_file(tmp_path):
    hub = tmp_path / "hub"
    scn = hub / "node-scenarios"
    scn.mkdir(parents=True)
    (scn / "env.sh").write_text('export FOO="${FOO:-x}"\n', encoding="utf-8")
    (scn / "krknctl-input.json").write_text('[{"variable": "FOO", "description": "from json"}]', encoding="utf-8")
    website = _site(tmp_path)
    out = website / "data/params/node-scenarios"
    out.mkdir(parents=True)
    (out / "krkn-hub.yaml").write_text(
        "# Generated by krkn-docs-bot. Do not edit by hand.\n"
        "source_repo: krkn-hub\nsource_ref: HEAD\n"
        "params:\n- name: FOO\n  description: hand written desc\n  default: x\n",
        encoding="utf-8")
    doc_bot.run(scenario="node-scenarios", krkn_hub_root=hub, website_root=website)
    # Was "hand written desc". The committed file is stamped "Do not edit by
    # hand", so letting it beat the source froze descriptions at first generation.
    assert _params(website, "node-scenarios")["FOO"]["description"] == "from json"


def _write_env(scn_dir):
    scn_dir.mkdir(parents=True, exist_ok=True)
    (scn_dir / "env.sh").write_text(
        'export ACTION="${ACTION:-node_stop}"\n'
        'export NEW_ONE="${NEW_ONE:-x}"\n', encoding="utf-8")


def test_emit_then_reemit_is_byte_identical(tmp_path):
    hub = tmp_path / "hub"
    _write_env(hub / "node-scenarios")
    website = tmp_path / "site"
    (website / "content/en/docs/scenarios").mkdir(parents=True)
    (website / "content/en/docs/scenarios/all-scenario-env.md").write_text("", encoding="utf-8")

    doc_bot.run(scenario="node-scenarios", krkn_hub_root=hub, website_root=website)
    out = website / "data/params/node-scenarios/krkn-hub.yaml"
    first = out.read_text(encoding="utf-8")

    # Second run must produce identical bytes. A param nothing describes is now
    # left blank rather than given a placeholder, and blank is falsy, so it stays
    # in the residual list and is offered to the resolver on every run. That is
    # fine: the resolver is a no-op in production and the output is unchanged.
    doc_bot.run(scenario="node-scenarios", krkn_hub_root=hub, website_root=website)
    assert out.read_text(encoding="utf-8") == first
