from pathlib import Path
import yaml

_HEADER = "# Generated by krkn-docs-bot. Do not edit by hand.\n"


def _param_dict(rec, description, source, scenario=None):
    d = {"name": rec.name, "description": description}
    # Globals live one file per source, so the group travels in the data and the
    # shortcode filters on it. Per-scenario params have no group and gain no key.
    if rec.group is not None:
        d["group"] = rec.group
    if rec.type is not None:
        d["type"] = rec.type
    if rec.default is not None:
        d["default"] = rec.default
    # Globals emit under "krknctl-<group>", per-scenario tables under "krknctl".
    if source.startswith("krknctl"):
        if rec.allowed_values:
            d["possible_values"] = list(rec.allowed_values)
    # Per-scenario krknctl only. Every global param is required=false, so emitting
    # it would add a sixth column of "False" to a five-column page. Globals share
    # the plain "krknctl" source name, so the scenario is what tells them apart.
    if source == "krknctl" and scenario != "globals":
        d["required"] = bool(rec.required)
    return d


def emit_data_text(scenario, source, records, descriptions, source_ref):
    body = {
        "source_repo": source,
        "source_ref": source_ref,
        "params": [_param_dict(r, descriptions[r.name], source, scenario) for r in records],
    }
    dumped = yaml.dump(body, sort_keys=False, default_flow_style=False,
                       allow_unicode=True, width=4096)
    return _HEADER + dumped


def load_descriptions(path):
    """name -> description from a previously generated data file, or {} if it does
    not exist. Reads what emit_data_file writes, so hand-edited wording survives
    regeneration."""
    path = Path(path)
    if not path.exists():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return {p["name"]: p.get("description", "") for p in data.get("params", [])}


def emit_data_file(out_root, scenario, source, records, descriptions, source_ref):
    path = Path(out_root) / "data" / "params" / scenario / f"{source}.yaml"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(emit_data_text(scenario, source, records, descriptions, source_ref),
                    encoding="utf-8")
    return path
